### ISSUE TITLE
Example on README.md doesn't work - Got undefined value

### ISSUE THREAD

**Issue by Unitech** [Wiredcraft/node-ejabberd#3]
Not a big issue but (I need to train me on issues posting :p): 

In the example, it is suggested to call directly addVhost :

``` javascript
var host = 'chat.example.com';
var config = {host: host};

// Add a virtual host to ejabberd's configuration then restart server
var p1 = e.addVhost(host, config);
```

But when we directly call addVhost, it pass on an undefined variable :
~l.139 in ejabberd.js file

``` javascript
if (!ejabberd.running) {
```

ejabberd.running is defined later on the initialize method (by true or false according to the state of ejabberd server).

It would be interesting to trigger an event when the initialize methods has finished his processing or to correct the example with something like in the branch joined

**Comment by kuno** [comment]
thx:

will take a look
